FROM node:22-alpine AS build

WORKDIR /app
COPY package*.json ./
RUN npm ci

COPY . .
RUN npm run build

FROM node:22-alpine AS runtime

WORKDIR /app
ENV NODE_ENV=production
ENV PORT=4000

COPY --from=build /app/dist/fyztech ./dist/fyztech

EXPOSE 4000
CMD ["node", "dist/fyztech/server/server.mjs"]
